name: Build Maven Java Project
on:
  push:
    branches:
      - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 'corretto-11'
          distribution: 'amazon'

      - name: Build with Maven
        run: mvn package