name: Unit Test Product api

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Run unit tests
        run: mvn test --batch-mode --no-transfer-progress
        working-directory: product-api/